#index:
#    path: /
#    controller: App\Controller\DefaultController::index
epotrade_website:
    resource: '../src/Routing/website.yaml'
    prefix: /

epotrade_backoffice:
    resource: '../src/Routing/backoffice.yaml'
    prefix: /dashboard